kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: build
  image: docker
  commands:
  - echo "Hello World!"
  - docker version
  - echo "Hello Dogi! This is a armhf drone runner!"

---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: build
  image: docker
  commands:
  - echo "Hello World!"
  - docker version
  - echo "Hello Dogi! This is a arm64 drone runner!"
