kind: pipeline
type: docker
name: arm-test

platform:
  arch: arm

steps:
- name: test
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - losetup -a
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-user-static dmsetup g++-arm-linux-gnueabihf nodejs git docker-ce -y
  - python3 -m pip install requests
  - dmsetup remove_all
  - losetup -D
  - bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive --armhf' # --arm64 or --armhf, need to implement in builder
  when:
    event:
      exclude:
        - tag
---
kind: pipeline
type: docker
name: arm-build

platform:
  arch: arm
steps:
- name: build
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  environment:
    ssh_deploy_key:
      from_secret: ssh_secret
  privileged: true
  commands:
  - losetup -a
  - apt-get update
  # - apt-get dist-upgrade -y
  # - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-user-static dmsetup g++-arm-linux-gnueabihf nodejs git docker-ce -y
  #- python3 -m pip install requests
  #- dmsetup remove_all
  #- losetup -D
  # - bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive --armhf'
  - echo "$ssh_deploy_key" | base64 --decode --ignore-garbage > .drone/id_deploy
  - git describe --tags | sed -e 's/^release-//'
  - .drone/environment.sh
  - echo "$experiment"
  - echo "$image_path"
  - .drone/compress.sh
  - .drone/upload.sh
  when:
    event:
      include:
        - tag

---
kind: pipeline
type: docker
name: arm64-test

platform:
  arch: arm64

steps:
- name: test
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - losetup -a
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-user-static dmsetup g++-aarch64-linux-gnu nodejs git docker-ce -y
  - python3 -m pip install requests
  - dmsetup remove_all
  - losetup -D
  - bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive --arm64'
  when:
    event:
      exclude:
        - tag

---
kind: pipeline
type: docker
name: arm64-build

platform:
  arch: arm64
steps:
- name: build
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  environment:
    ssh_deploy_key:
      from_secret: ssh_secret
  privileged: true
  commands:
  - losetup -a
  - apt-get update
  #- apt-get dist-upgrade -y
  #- apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-user-static dmsetup g++-aarch64-linux-gnu nodejs git docker-ce -y
 # - python3 -m pip install requests
 # - dmsetup remove_all
 # - losetup -D
  #- bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive --arm64'
  - echo "$ssh_deploy_key" | base64 --decode --ignore-garbage > .drone/id_deploy
  - git describe --tags | sed -e 's/^release-//'
  - .drone/environment.sh
  - echo "$experiment"
  - echo "$image_path"
  - .drone/compress.sh
  - .drone/upload.sh
  when:
    event:
      include:
        - tag

---
kind: secret
name: api_key
data: oQcHB87i8xm+rxKZHAw4eGZgLjhwjAQB25IvPc9L1uOHopL8Sf/zt+UTkQAZzAiS+ompEdEdt6Biecd4onUX7JpJNsY=
---
kind: secret
name: ssh_secret
data: 1pr0ibCQHmTknfiuCBb/KspXsz9GNPExqvPDLJH6DuqdB0/DHOkIC7MdKwdKv2YHUQr43F1uJ5ycZGFVFHullW563EbcKZD6GTLKDTseXfUJFhYrMREIj9BQOwHUBbvaCSPF4UN8xbHMo3scnaxwrCj/fhx2zV4v7wEfbQXItSHLzSP0eZWK4uvPeLiS5lSU5xCtn07vcDfoGuzBuB7f1NF47uqQG6ODA4WG+uz+/Gdgka/lH/glCvecUUtGhJg+4b4rt5RVbrrkNupT5yadn4tSGF0mHRVKLcrweqm++d+xHe73Xf7yLrocCKeh8pLptvziPF4///g1iATLlhtAA7Y42A/HQI3Wz0jz8LanBY7THn3E+00+BoSE3m6r/Ln6oXQY1VhjlfudgoSDmEUEwgjDJGUxp0cOb2C5WfX0EqrxSBT7hkxj1AuPNRFeEKIa/q1yceLb9sRQA6tXV1yhgR6cz0e2RY2fl9CVtlWa/1jHwtz5obaTuzGAo14ileFYA/EZL8OIgJ8LSwvkSXlv+G+qtvtHBxpuZCBIKRIjq1j/JbomzJwMOYB4TimbhvJmfEzxJsCOZlXO0OGkvWYGhIShuPocSDmv