kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: build
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip -y
  - python3 -m pip install requests
  - ./builder --noninteractive
  - ./.travis/compress.sh

---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: build
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip -y
  - python3 -m pip install requests
  - ./builder --noninteractive
  - ./.travis/compress.sh

---
kind: secret
name: api_key
data: oQcHB87i8xm+rxKZHAw4eGZgLjhwjAQB25IvPc9L1uOHopL8Sf/zt+UTkQAZzAiS+ompEdEdt6Biecd4onUX7JpJNsY=