kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: build
  image: golang
  commands:
  - echo "Hello World!"
  - apt-get update
  - apt-get install kpartx qemu-user-static parted wget curl jq aria2 -y
  - ./builder --noninteractive
  - ./.travis/compress.sh

---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - echo "Hello World!"
  - go version
  - echo "Hello Dogi! This is a arm64 drone runner!"
