kind: pipeline
type: docker
name: armhf

platform:
  arch: armhf

steps:
- name: build
  image: golang
  commands:
  - echo "Hello World!"
  - go version
  - go build
  - go test

---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - echo "Hello World!"
  - go version
  - go build
  - go test
