kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: build
  image: golang
  privileged: true
  commands:
  - echo "Hello World!"
  - apt-get update
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 -y
  - apt-get dist-upgrade -y
  - ./builder --noninteractive
  - ./.travis/compress.sh

---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: build
  image: golang
  privileged: true
  commands:
  - echo "Hello World!"
  - apt-get update
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 -y
  - apt-get dist-upgrade -y
  - ./builder --noninteractive
  - ./.travis/compress.sh
