kind: pipeline
type: docker
name: arm-test

platform:
  arch: arm

steps:
- name: test
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - echo "$GITHUB_KEY"
  - df -h
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-user-static -y
  - python3 -m pip install requests
  - bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive' # --arm64 or --armhf, need to implement in builder

---
kind: pipeline
type: docker
name: arm-build

platform:
  arch: arm
steps:
- name: build
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-user-static -y
  - python3 -m pip install requests
  - bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive'
  - ./.travis/compress.sh
  - ./.travis/upload.sh
  when:
    event:
      include:
        - tag

---
kind: pipeline
type: docker
name: arm64-test

platform:
  arch: arm64

steps:
- name: test
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - echo "$GITHUB_KEY"
  - df -h
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-user-static -y
  - python3 -m pip install requests
  - bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive'

---
kind: pipeline
type: docker
name: arm64-build

platform:
  arch: arm64
steps:
- name: build
  image: golang
  environment:
    GITHUB_KEY:
      from_secret: api_key
  privileged: true
  commands:
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install kpartx parted wget curl jq aria2 unzip python3 python3-pip qemu-arm-static -y
  - python3 -m pip install requests
  - bash -c 'export GITHUB_KEY="$GITHUB_KEY";mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive'
  - ./.travis/compress.sh
  - ./.travis/upload.sh
  when:
    event:
      include:
        - tag

---
kind: secret
name: api_key
data: oQcHB87i8xm+rxKZHAw4eGZgLjhwjAQB25IvPc9L1uOHopL8Sf/zt+UTkQAZzAiS+ompEdEdt6Biecd4onUX7JpJNsY=