kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: build
  image: golang
  user: root
  commands:
  - echo "Hello World!"
  - apt-get update
  - apt-get install kpartx parted wget curl jq aria2 unzip -y
  - ./builder --noninteractive
  - ./.travis/compress.sh

---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: build
  image: golang
  user: root
  commands:
  - echo "Hello World!"
  - go version
  - echo "Hello Dogi! This is a arm64 drone runner!"
