sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - kpartx
      - qemu-user-static
      - aria2
      - tree

install:
  - sudo service docker stop && sudo rm -rf /var/lib/docker && sudo service docker start

script: mkdir images && sudo PATH=./node_modules/.bin:$PATH ./builder --noninteractive

env:
  global:
    - secure: "ukHo+YrG6xulVlk3WuZd9ITOlbUiCKEApWZdy0pHkSb5QvOh4k92aPkQfNYec3Kvy878FaRY4jog2EzYCOfnuuGPilKlywgsEAajr5Ox3wj082D2plRsDVW3UjaHaeUxQjJw5yRPfjd1k3MFJfLrVMS2J8Uf0DzCFlnjAdm77AF+MrQN1HP2XdzWb3AkPqHAE/IgxdJqVf6dlgSerl1cAHhqeLvA2gR4HJPPmPc5OYEH+QCMOmNJ2zONjKd5W3mnZlQwnVJ2AcfT7L7w68uqvS/IulPhWXjFy6VSOYi7HJRxezPzf7thL5W/0z8oCcUPvTgbePNAq+g7N3nP6QGDwdYsTzrWoRTwkcpPkB9biWOwXv+TgAD3PyptWUX9XfgAYfsN4iUBKYqSTiNMsknEdo1YAQCxQomZdELkBfrjxYzXXfeoqv44c2fUUBLso5siDhs+9R1k76JeHFpOObUmwlGBHf/TM9LUhaHTdSSIoscxo44VmHSkx06kUwxvKJVNzRQPJdJQK6phLKf4W4bwiRlX+6mh2Y/El2uTfqv2fNmLVvTpQOa0e5BqO4WpONxWVBIerl//Ccxk3SEdfCbxeLQaDwFeMf0k7NvxF6HNslao0Mp9TutIvYaDWtig+TaVO4X5bA4pNCno0i9EwWcs3MNHFtspCdol3GuSHbM6HO8="
    - secure: "Sp5p4hPIDWIUUkcqFSKBRB96Iw6VaR7iZGbNI6fh6zLcJBDU+rzq9NAOGoFvy08R/URKTNWXj5stGx9627V7C+QRvMy/BtOzbOfmRJCQwUb1oOE+dCSXruWW/8TutAUo1m3tK97nXm2AzbIbL5r0xkOOTevX30Wu6TkDdLllaUDfsbulzWQsIuQT2GEzetlc3ZsKA4E1kG6/LqKRA7MHMho9koSq1PWVlc8J+33qVEeBXBPh6aMQDZOBfu6fo/bfaAwhXY4INH/ilyPE17lV4sz7IriFWyram4O8xGOLMN6qB3nexZ/5vCeEq3fuMAA9tx9tpnD41K2RP42vPSgNTyw7BfApFFbYpN0INr9Einn8XZaft9DZgb8za2YGSmyKQYfjpnlQausQfiimSLAAY9ir1X0AJcVAvPFGBVASE5mUrFrBvRvspfvJJKxMYzCdumDePrpEh+c9ikuQjDeFcUHoMfJP9z5HDmesffkiOPpcP089Kq50km3nxVyZL9Ep9yPBKmlkz62zgg/WiYjkACDWyH1nmYcDqM1gYOJS4/10wAMKZJDQ6aJy/024IBXRaIYShYkz3svvWyG8rt5ky2mpkGMbMWwQc5prb46nNg8IzXtBUjTepU9QVaQCvN9/2xbz6lZq/WUhZ9YgizFIy8UCkXFLvVP7z2zwc5CUqv0="

before_deploy:
  - echo "$ssh_deploy_key" | base64 --decode --ignore-garbage > .travis/id_deploy

deploy:
  - provider: script
    skip_cleanup: true
    script: ./.travis/deploy.sh
    on:
      all_branches: true
      tags: true
  - provider: s3
    access_key_id: AKIAISP267FQ2JXEHXYA
    secret_access_key:
      secure: F19gjiskDLh2/qjRVjgJhIJlV1vE5yY5ugBrYVL+V+jzWzUA2Er018/fMLLIYpOnwlbsSkHrnn9x48MmFurka5CBe99cuopc8Dl15+ufqb7GMX1zdq7/CWL6h1AAtI97+uZTLMV3K+HAa5jRofOQq9xyNlkb/Gj/SumPvxxzeeA7np8NU6TmHRCt6p3oI9Xc9Su9ojabL4wvuNUvbkPcsHhxkQV8fpfAonzOutG2a4CaNx3BSxjvDN6/ZzqE/NkwvfMLKjfniCXyFfs7n1RA1DmyG5EWnTa0OTRvDutaAdQuPIj5nNCh1vV9ebHn3nH2ywGGvTLGjOmqzPGVA+sGDbqZSEDa/GwR543NnGQO0o1XAAVZ5cc9yYlzqg2u1rISCxfJStf2Hf+ONJV0zWuENizX6yqG/4N/BPnH0Kuxkw18N/wLQKlt//rN+S2hBV6TcuVwTQFpUbfhZK0Bm9KmC+N9L1aEjooF/zLGLWoWWaYoUQkwsSsLxv1c/+mOCvuvDDDuMTRjR49dvEtXf/8Ntk+3lC/ZsKhlEl12zemxLqFH0KkRX7aedcsHs83+KCFxNynedIt3uShmPVuG8sWZQOMsaRZ20XO7LvFwd+XKDRMg5WkHktvTnSUP7xFCNJBL3eKzo2sCx6/VYFVBql2n2rOWL7c2h2FVAXKTTYy/aEI=
    bucket: treehouses
    local-dir: build
    skip_cleanup: true


notifications:
  webhooks:
    urls:
      secure: "Aqo5s4yLOboXOWnK2WfafKQidLe/dlyOEt3hZbQqSX7XiiNgfTaUjkmFJjQrpMcx0lShlW0amd5UadvDbu5PFajaSqW7xagpxTof0w6JWTlaVseQ38olpXn1IgDqJH679ZnOQYpoFKNnvvgQNJ9+xs4lCDitQc+aHVdhVVfxBGQQtj+AOBv6+ILciTCmk+ComzbLjUxSj/TWnao2kR+x2GyXwZ7l3TXnX1/2/c9LCAwh9oA9t5nvvuZBoj3Uk1XHQWpFzfMEltOdCgYyhVqOddlfDNch7HqeHZQU0Y+B9zm3v4lM8s4DaX7gfofjw4yKi5Uj+pT+KePNNIjv+OPsyiXWqhIA7X2N4OSgbr7Fbvlf/IM3vPL+7Su7UtvR5mLUPMa+jEGARsJE68IOpss+oy2x2u2AHKKRA9rtGacVNPt/2EPMZiXSqGRsclft3dEVNEM4ryOZJNg/XHbPNtxEpKsBhPwD1ZpBkp/2NWNojpMTdUbYln1cEwcP6vl+c1KwJsbGs8tjm7ojuGmhAVHDdvm1WsVClROypgjsKiO17lOKOknq3Bv74L8s25Vz0ffDdcaHC2PBvNk2gTbl7Eu675rHujhcHZjXbw1UaTcNO9ZqlQTFXn72x76rIGmuopzKrouxdqAwJe5L2tFjAWYq+8m7/k+ZeuEG2vdDvss9vGc="
      on_success: always # one of: always, never, change
      on_failure: always
      on_start: never
