sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - kpartx
      - qemu-user-static
      - aria2

install:
  - sudo service docker stop && sudo rm -rf /var/lib/docker && sudo service docker start

script: mkdir images && sudo PATH=./node_modules/.bin:$PATH ./treehouse-builder --noninteractive

env:
  secure: "XGvxhP/wHifsawXvUouCDWmkuLEq7Bn56Yh+ntVRlWTP0f0kULT5Nj/zw5tIAK0Rt5WKGIdIO+bUhOl7zOpKexdWDQIiXOCQTU4NieV6Mm9VxM/U0A81HHkcKxqS0JDyVfOhXTxAx+3cr0ggMhMJb0q+CpNkLxdzvsK0Te97Afh0lf27RAfNP/AoELegd8OPVeOheXwlw/+aFpsIwQ56NGhngXx4CqPe0tFTt5eTWcKxdFbXINZLDcU/EUt4th6EKtlXgbgmKOmL3qV/dpX30MtjMmtxixh/YK+sMyZ8VY+IylWoD8FgsyHzVNL4m0W7dpGJyKlrai9v7JUe5WB+ut2eqpJWesyC32dMUXTIAZryV64t0ZYW4TQP1rTrLLIjSoFyHEmpfni3F9tCvLcrobk798CjT0Cl26MinMOkoZ1ih0vd5lfeMrc/B4Eq/YVNDnUY5xBNPBgNVr8EvcSPHFxeIF8cBf+3OSRLGuc6EoQ0auBfDA14jtAnSqrRa0JFPISWVCrhDga+sDw9fKFBLSInoo1g/GnqwosGBpWq6BY+9FYrzWkYhkdAEGjETn/lBfcjDWkKKDQdqzvEEraYLDhw/UWiBGlbAM+0KVxNtO4clQxZH8vmQFu0J8K0LlekoXb9TSUsAnlFD2OtdYL0pMok9/H50ree/ib0Q5SQklY="

before_deploy:
  - echo "$ssh_deploy_key" > .travis/id_deploy

deploy:
  provider: script
  skip_cleanup: true
  script: ./.travis/deploy.sh
  on:
    all_branches: true
    tags: true

notifications:
  webhooks:
    urls:
      secure: "Aqo5s4yLOboXOWnK2WfafKQidLe/dlyOEt3hZbQqSX7XiiNgfTaUjkmFJjQrpMcx0lShlW0amd5UadvDbu5PFajaSqW7xagpxTof0w6JWTlaVseQ38olpXn1IgDqJH679ZnOQYpoFKNnvvgQNJ9+xs4lCDitQc+aHVdhVVfxBGQQtj+AOBv6+ILciTCmk+ComzbLjUxSj/TWnao2kR+x2GyXwZ7l3TXnX1/2/c9LCAwh9oA9t5nvvuZBoj3Uk1XHQWpFzfMEltOdCgYyhVqOddlfDNch7HqeHZQU0Y+B9zm3v4lM8s4DaX7gfofjw4yKi5Uj+pT+KePNNIjv+OPsyiXWqhIA7X2N4OSgbr7Fbvlf/IM3vPL+7Su7UtvR5mLUPMa+jEGARsJE68IOpss+oy2x2u2AHKKRA9rtGacVNPt/2EPMZiXSqGRsclft3dEVNEM4ryOZJNg/XHbPNtxEpKsBhPwD1ZpBkp/2NWNojpMTdUbYln1cEwcP6vl+c1KwJsbGs8tjm7ojuGmhAVHDdvm1WsVClROypgjsKiO17lOKOknq3Bv74L8s25Vz0ffDdcaHC2PBvNk2gTbl7Eu675rHujhcHZjXbw1UaTcNO9ZqlQTFXn72x76rIGmuopzKrouxdqAwJe5L2tFjAWYq+8m7/k+ZeuEG2vdDvss9vGc="
      on_success: always # one of: always, never, change
      on_failure: always
      on_start: never
